#!/bin/bash
CUR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

case $(uname) in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${OPT}"
esac

echo Info: running on $machine

marker="##environment installed"
install_bashrc() {
	if [[ $machine == "Mac" ]]; then
		echo "Updating .bash_profile (mac)"
		echo "$marker" >> ~/.bash_profile
		echo "source $CUR_DIR/.bash_profile" >> ~/.bash_profile
	else
		echo "Updating .bashrc"
		echo "$marker" >> ~/.bashrc
		echo "source $CUR_DIR/.bashrc" >> ~/.bashrc
	fi
}

install_vim() {
    echo "Updating vim"
    [[ ! -d ~/.vim ]] && mkdir ~/.vim
    for f in $(find $CUR_DIR/.vim -maxdepth 1 -type d); do
        ln_target="$HOME/.vim/$(basename "$f")"
        [[ ! -h "$ln_target" ]] && ln -s $f "$ln_target"
    done
    [[ ! -f ~/.vimrc ]] && ln -s $CUR_DIR/.vimrc ~/.vimrc
}

install_vim

if ! grep -q "$marker" ~/.bashrc ~/.bash_profile 2>/dev/null; then
    install_bashrc
fi

git submodule init
git submodule update
