#!/bin/bash
CUR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

install_bashrc() {
    echo "Updating .bashrc"
    echo "source $CUR_DIR/.bashrc" >> ~/.bashrc
}

install_vim() {
    echo "Updating vim"
    [[ ! -d ~/.vim ]] && mkdir ~/.vim
    for f in $(find $CUR_DIR/.vim -maxdepth 1 -type d); do
        ln_target="$HOME/.vim/$(basename "$f")"
        [[ ! -h "$ln_target" ]] && ln -s $f "$ln_target"
    done
    [[ ! -f ~/.vimrc ]] && ln -s $CUR_DIR/.vimrc ~/.vimrc
}

install_vim

if ! grep -q "/$( basename "$CUR_DIR")/.bashrc" ~/.bashrc; then
    install_bashrc
fi

git submodule init
git submodule update
